# TANDEM 
  # gradio_app: port 7861
# TANDEM-dev : port 7862
# always : docker compose down
# unless-stopped : docker compose stop

services:
  gradio_app:
    restart: always
    build: ./gradio_app
    container_name: gradio_app
    ports:
      - "7861:7861"
    volumes:
      - ./gradio_app:/gradio_app
      - ./tandem:/tandem
    depends_on:
      - mongodb
      - worker
      - tandem1
      - tandem2
      - tandem3
      - tandem4
    labels:
      owner: "loci"

  tandem1: &tandem_service
    restart: always
    platform: linux/amd64
    build: ./tandem
    container_name: tandem_1
    expose:
      - "5000" # internal only; not mapped to host
    depends_on:
      - mongodb
      - polyphen2
    volumes:
      - ./tandem:/tandem
      - ./gradio_app:/gradio_app
    labels:
      owner: "loci"

  tandem2:
    <<: *tandem_service
    container_name: tandem_2

  tandem3:
    <<: *tandem_service
    container_name: tandem_3

  tandem4:
    <<: *tandem_service
    container_name: tandem_4

  polyphen2:
    restart: always
    platform: linux/amd64
    build:
      context: ./tandem/PolyPhen-2
      dockerfile: Dockerfile
    container_name: pph2
    expose:
      - "5001"
    volumes:
      - ../tandem_website_dev/tandem/PolyPhen-2:/pph2
      - ./tandem:/tandem
    labels:
      owner: "loci"

  worker:
    restart: always
    build: ./worker
    container_name: worker
    depends_on:
      - mongodb
      - tandem1
      - tandem2
      - tandem3
      - tandem4
    environment:
      TANDEM_URLS: "http://tandem1:5000/run_tandem_job,http://tandem2:5000/run_tandem_job,http://tandem3:5000/run_tandem_job,http://tandem4:5000/run_tandem_job"
    volumes:
      - ./worker:/worker
      - ./tandem:/tandem
    labels:
      owner: "loci"

  mongodb:
    restart: always
    image: mongo:8
    container_name: mongodb
    ports:
      - "27017:27017"
    labels:
      owner: "loci"