# TANDEM 
  # gradio_app: port 7861
# TANDEM-dev : port 7862
# always : docker compose down
# unless-stopped : docker compose stop

services:
  gradio_app:
    restart: always
    build: ./gradio_app
    container_name: gradio_app
    ports:
      - "7861:7861"
    volumes:
      - ./gradio_app:/gradio_app
      - ./tandem:/tandem
    depends_on:
      - mongodb
      - worker
      - tandem
    labels:
      owner: "yang_loci"
      project: "tandem_website"

  tandem:
    restart: always
    platform: linux/amd64
    build: ./tandem
    container_name: tandem
    expose:
      - "5000"   # internal only; not mapped to host
    depends_on:
      - mongodb
    volumes:
      - ./tandem:/tandem
      - ./gradio_app:/gradio_app
    labels:
      owner: "yang_loci"
      project: "tandem_website"

  worker:
    restart: always
    build: ./worker
    container_name: worker
    depends_on:
      - mongodb
      - tandem
    volumes:
      - ./worker:/worker
      - ./tandem:/tandem
    labels:
      owner: "yang_loci"
      project: "tandem_website"

  mongodb:
    restart: always
    image: mongo:8
    container_name: mongodb
    ports:
      - "27017:27017"
    labels:
      owner: "yang_loci"
      project: "tandem_website"