# TANDEM gradio_app: port 7861
# TANDEM-dev gradio_app : port 7862

services:
  gradio_app:
    restart: always
    build: ./gradio_app
    container_name: gradio_app_dev
    ports:
      - "7862:7861"
      # - "7890:7890"
    volumes:
      - ./gradio_app:/gradio_app
      - ./tandem:/tandem
    depends_on:
      - mongodb
      - worker
      - tandem1
      - tandem2
      - tandem3
      - tandem4
    labels:
      owner: "loci"

  tandem1: &tandem_service
    restart: always
    platform: linux/amd64
    build: ./tandem
    expose:
      - "5000" # internal only; not mapped to host
    depends_on:
      - mongodb
      - polyphen2
    volumes:
      - ./tandem:/tandem
      - ./gradio_app:/gradio_app
      - ../tandem_website/tandem/data/consurf/uniref90.fasta:/tandem/data/consurf/uniref90.fasta:ro
    labels:
      owner: "loci"

  tandem2:
    <<: *tandem_service

  tandem3:
    <<: *tandem_service

  tandem4:
    <<: *tandem_service

  polyphen2:
    restart: always
    platform: linux/amd64
    build:
      context: ./tandem/PolyPhen-2
      dockerfile: Dockerfile
    container_name: pph2_dev
    expose:
      - "5001"
    volumes:
      - ./tandem/PolyPhen-2:/pph2
      - ./tandem:/tandem
    labels:
      owner: "loci"

  worker:
    restart: always
    build: ./worker
    container_name: worker_dev
    depends_on:
      - mongodb
      - tandem1
      - tandem2
      - tandem3
      - tandem4
    environment:
      TANDEM_URLS: "http://tandem1:5000/run_tandem_job,http://tandem2:5000/run_tandem_job,http://tandem3:5000/run_tandem_job,http://tandem4:5000/run_tandem_job"
    volumes:
      - ./worker:/worker
      - ./tandem:/tandem
      - ../tandem_website/tandem/data/consurf/uniref90.fasta:/tandem/data/consurf/uniref90.fasta:ro
    labels:
      owner: "loci"

  mongodb:
    restart: always
    image: mongo:8
    container_name: mongodb_dev
    labels:
      owner: "loci"
